name: CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Instalar Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # 3. Instalar dependencias
      - name: Install dependencies
        run: bun install --frozen-lockfile

      # 4. Verificar TypeScript
      - name: Check TypeScript
        run: bun run check

      # 5. Ejecutar ESLint
      - name: Run ESLint
        run: bun run lint

      # 6. Ejecutar Build de Svelte
      - name: Run Build
        run: bun run build
